# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P8VG7NZz7_Xj1p5YYH3V4bPVwkTmniWx
"""

!pip install pandas scikit-learn

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

#loading the csv data to a Pandas DataFrame
iris_data = pd.read_csv('ContactLens.csv')

#print first 5 rows of dataset
iris_data.head()

#print first 5 rows of dataset
iris_data.tail()

iris_data.shape

#getting some info about data
iris_data.info()

#checking for missing values
iris_data.isnull().sum()

#statistical measures about the data
iris_data.describe()

iris_data['TearProdRate'].value_counts()

X = iris_data.drop(columns='TearProdRate',axis=1)
Y = iris_data['TearProdRate']

print(X)

print(Y)